# Generated by Django 2.1.2 on 2018-10-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpers_nurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('flag', models.IntegerField()),
                ('contact', models.CharField(max_length=12)),
                ('allotted_doctor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1200)),
                ('last_name', models.CharField(max_length=1200)),
                ('guardian_name', models.CharField(max_length=1200)),
                ('city', models.CharField(default='NULL', max_length=1200)),
                ('state', models.CharField(default='NULL', max_length=1200)),
                ('country', models.CharField(default='NULL', max_length=1200)),
                ('country_code', models.CharField(default='+91', max_length=120)),
                ('zip_code', models.CharField(default='NULL', max_length=120)),
                ('phone_number', models.CharField(max_length=1200)),
                ('date', models.CharField(default='NULL', max_length=120)),
                ('address', models.CharField(max_length=1200)),
                ('problem_name', models.CharField(max_length=1200)),
                ('assigned_doctor', models.CharField(max_length=1200)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(max_length=12000)),
                ('blood_pressure', models.CharField(default='NULL', max_length=1200)),
                ('weight', models.CharField(default='NULL', max_length=1200)),
                ('sugar', models.CharField(default='NULL', max_length=1200)),
                ('medicine', models.CharField(max_length=1200)),
                ('morning_intake', models.BooleanField(default=False)),
                ('afternoon_intake', models.BooleanField(default=False)),
                ('evening_intake', models.BooleanField(default=False)),
                ('days', models.IntegerField()),
                ('tests', models.CharField(max_length=1200)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hospital_automation.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
                ('specialization', models.CharField(default='NULL', max_length=1200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
