# Generated by Django 2.1.1 on 2018-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='NULL', max_length=1200),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='NULL', max_length=1200),
        ),
        migrations.AddField(
            model_name='patient',
            name='country_code',
            field=models.CharField(default='+91', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='NULL', max_length=1200),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(default='NULL', max_length=120),
        ),
    ]
