# Generated by Django 2.1.1 on 2018-10-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_automation', '0002_auto_20181015_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='NULL', max_length=120),
        ),
    ]
