# Generated by Django 2.1.1 on 2018-10-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_automation', '0002_patient_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hospital_automation.Patient'),
        ),
    ]
